#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service()
{
    procd_open_instance
    procd_set_param command hass-configurator -s -b /mnt/mmcblk0p1/domoticz/homeassistant/config
    procd_set_param stdout 1
	procd_set_param stderr 1
    procd_close_instance
}