#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1


section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}
service_triggers() {
	procd_add_reload_trigger homeassistant
}
start_instance() {
	local cfg="$1"	
	
	if ! section_enabled "$cfg"; then
		echo "disabled in config"
		return 1
	fi	


    procd_open_instance
    procd_set_param command hass-configurator -s -b /mnt/mmcblk0p1/domoticz/homeassistant/config
    procd_set_param stdout 1
	procd_set_param stderr 1
    procd_close_instance
	
	 
}

start_service() {
	config_load 'homeassistant'
	config_foreach start_instance 'homeassistant'
}

stop_instance() {  
	local cfg="$1"

	
}

stop_service() {
	config_load 'homeassistant'
	config_foreach stop_instance 'homeassistant'
}

